# This is an example configuration file for Redpanda Console v3.x.x

#----------------------------------------------------------------------------
# Kafka configuration
#----------------------------------------------------------------------------
kafka:
  # Brokers is a list of bootstrap servers with ports.
  brokers:
    - "kafka-broker-01:19092"
    - "kafka-broker-02:19092"
    - "kafka-broker-03:19092"
  # Optional: Client ID used to identify Redpanda Console to the Kafka cluster.
  clientId: "console"

#----------------------------------------------------------------------------
# Kafka Connect configuration (optional)
#----------------------------------------------------------------------------
kafkaConnect:
  enabled: true
  connectTimeout: 15s
  readTimeout: 60s
  requestTimeout: 6s
  clusters:
    - name: clickHouse-connect
      url: "http://kafka-connect:8083"

#----------------------------------------------------------------------------
# Redpanda Console settings
#----------------------------------------------------------------------------
console:
  topicDocumentation:
    enabled: false

#----------------------------------------------------------------------------
# Server settings
#----------------------------------------------------------------------------
server:
  listenAddress: "0.0.0.0"
  listenPort: 8080
  httpsListenPort: 8081
  advertisedHttpsListenPort: 443
  gracefulShutdownTimeout: 30s
  readTimeout: 30s
  writeTimeout: 30s
  idleTimeout: 30s
  compressionLevel: 4
  basePath: ""
  setBasePathFromXForwardedPrefix: true
  stripPrefix: true
  tls:
    enabled: false
  allowedOrigins: []

#----------------------------------------------------------------------------
# Logger settings
#----------------------------------------------------------------------------
logger:
  level: info