jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123

taskmanager.numberOfTaskSlots: 2
parallelism.default: 2

rest.address: jobmanager
rest.port: 8081
jobmanager.bind-host: 0.0.0.0
taskmanager.bind-host: 0.0.0.0

jobmanager.memory.process.size: 1600m
taskmanager.memory.process.size: 1728m
env.java.opts.all: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED